# Generated by Django 4.1.1 on 2022-09-20 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('S', 'Spirit'), ('R', 'Sour'), ('F', 'Fizz'), ('M', 'Smash'), ('P', 'Syrup'), ('B', 'Bitters'), ('H', 'Herb'), ('J', 'Juice'), ('G', 'Garnish'), ('O', 'Other')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(max_length=1000)),
                ('skill_level', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], default='I', max_length=1)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.drink')),
                ('ingredients', models.ManyToManyField(to='main_app.ingredient')),
            ],
        ),
    ]
