# Generated by Django 4.1.1 on 2022-09-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_recipe_ingredients_recipe_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('S', 'Spirit'), ('R', 'Sour'), ('F', 'Fizz'), ('M', 'Smash'), ('P', 'Syrup'), ('B', 'Bitters'), ('H', 'Herb'), ('J', 'Juice'), ('G', 'Garnish'), ('O', 'Other')], default='S', max_length=1),
        ),
    ]
