# Generated by Django 4.1.1 on 2022-09-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_ingredient_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.ingredient',),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='main_app.recipeingredient'),
        ),
    ]
